spring.application.name=training


spring.kafka.bootstrap-servers=lale1.mkk.com.tr:19092,lale2.mkk.com.tr:19092,lale3.mkk.com.tr:19092
spring.kafka.consumer.bootstrap-servers=lale1.mkk.com.tr:19092,lale2.mkk.com.tr:19092,lale3.mkk.com.tr:19092
